# Data cleaning and feature engineering

In [1]:
# import libraries
import numpy as np
import pandas as pd

In [2]:
# read the dataframe
df = pd.read_csv('../data/Raw_Neiva_Solcast_PT60M.csv')

In [3]:
# printout the column names
df.columns

Index(['PeriodEnd', 'PeriodStart', 'Period', 'AirTemp', 'Dhi', 'Dni', 'Ghi',
       'PrecipitableWater', 'RelativeHumidity', 'SurfacePressure',
       'WindDirection10m', 'WindSpeed10m'],
      dtype='object')

In [4]:
# select some features
df = df[['PeriodEnd', 'PeriodStart', 'AirTemp', 'Dhi', 'Dni', 'Ghi',
       'PrecipitableWater', 'RelativeHumidity', 'SurfacePressure',
       'WindDirection10m', 'WindSpeed10m']]

In [5]:
# randomly display 10 rows
df.sample(10)

,PeriodEnd,PeriodStart,AirTemp,Dhi,Dni,Ghi,PrecipitableWater,RelativeHumidity,SurfacePressure,WindDirection10m,WindSpeed10m
176,2020-01-07T10:00:00Z,2020-01-07T09:00:00Z,19.4,0,0,0,33.3,84.6,919.6,165,0.3
5120,2020-07-31T10:00:00Z,2020-07-31T09:00:00Z,20.2,0,0,0,40.2,74.3,920.2,202,1.5
5291,2020-08-07T13:00:00Z,2020-08-07T12:00:00Z,23.3,149,31,159,35.8,58.3,923.0,199,2.2
4078,2020-06-18T00:00:00Z,2020-06-17T23:00:00Z,20.9,1,0,1,45.0,86.3,920.0,195,1.1
5825,2020-08-29T19:00:00Z,2020-08-29T18:00:00Z,30.4,180,743,866,36.9,39.3,917.6,27,1.9
708,2020-01-29T14:00:00Z,2020-01-29T13:00:00Z,23.1,261,39,278,38.4,79.1,922.2,326,0.2
17054,2021-12-10T16:00:00Z,2021-12-10T15:00:00Z,24.9,381,0,381,43.3,75.9,919.6,15,1.3
10821,2021-03-25T23:00:00Z,2021-03-25T22:00:00Z,26.6,51,214,97,42.6,61.3,916.3,205,0.2
4498,2020-07-05T12:00:00Z,2020-07-05T11:00:00Z,20.0,30,245,72,39.2,78.2,921.0,183,0.2
5427,2020-08-13T05:00:00Z,2020-08-13T04:00:00Z,22.7,0,0,0,41.2,63.8,918.3,176,1.4

In [6]:
old_names = ['PeriodEnd', 'PeriodStart', 'AirTemp', 'Dhi', 'Dni', 'Ghi','PrecipitableWater', 'RelativeHumidity',
             'SurfacePressure', 'WindDirection10m', 'WindSpeed10m'] 
new_names = ['PeriodEnd','PeriodStart','Temperature', 'DHI', 'DNI', 'Radiation', 'Precipitation', 'Humidity', 
             'Pressure', 'WindDirection', 'WindSpeed']
df.rename(columns = dict(zip(old_names, new_names)), inplace = True)

In [7]:
# display dataframe
df.head()

,PeriodEnd,PeriodStart,Temperature,DHI,DNI,Radiation,Precipitation,Humidity,Pressure,WindDirection,WindSpeed
0,2019-12-31T02:00:00Z,2019-12-31T01:00:00Z,22.9,0,0,0,47.1,74.8,917.6,99,1.3
1,2019-12-31T03:00:00Z,2019-12-31T02:00:00Z,22.3,0,0,0,47.8,78.4,918.3,97,1.2
2,2019-12-31T04:00:00Z,2019-12-31T03:00:00Z,21.7,0,0,0,48.6,83.7,918.7,108,1.0
3,2019-12-31T05:00:00Z,2019-12-31T04:00:00Z,21.4,0,0,0,48.9,86.5,918.9,138,0.7
4,2019-12-31T06:00:00Z,2019-12-31T05:00:00Z,21.1,0,0,0,48.4,87.5,918.8,177,0.6

In [8]:
# show a summary of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17205 entries, 0 to 17204
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PeriodEnd      17205 non-null  object
 1   PeriodStart    17205 non-null  object
 2   Temperature    17205 non-null  float64
 3   DHI            17205 non-null  int64
 4   DNI            17205 non-null  int64
 5   Radiation      17205 non-null  int64
 6   Precipitation  17205 non-null  float64
 7   Humidity       17205 non-null  float64
 8   Pressure       17205 non-null  float64
 9   WindDirection  17205 non-null  int64
 10  WindSpeed      17205 non-null  float64
dtypes: float64(5), int64(4), object(2)
memory usage: 1.4+ MB

In [9]:
 # interpret columns as appropriate data types to ensure compatibility
df['Radiation']     = df['Radiation'].astype(float)
df['Temperature']   = df['Temperature'].astype(float) # or int
df['Pressure']      = df['Pressure'].astype(float)
df['Humidity']      = df['Humidity'].astype(int) # or int
df['WindDirection'] = df['WindDirection'].astype(float)
df['WindSpeed']     = df['WindSpeed'].astype(float)
df['PeriodStart'] = pd.to_datetime(df['PeriodStart']).dt.to_period('T').dt.to_timestamp()
df['PeriodEnd'] = pd.to_datetime(df['PeriodEnd']).dt.to_period('T').dt.to_timestamp()

/home/richardc7/.local/lib/python3.9/site-packages/pandas/core/arrays/datetimes.py:1143: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  warnings.warn(

In [10]:
# display dataframe summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17205 entries, 0 to 17204
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PeriodEnd      17205 non-null  datetime64[ns]
 1   PeriodStart    17205 non-null  datetime64[ns]
 2   Temperature    17205 non-null  float64
 3   DHI            17205 non-null  int64
 4   DNI            17205 non-null  int64
 5   Radiation      17205 non-null  float64
 6   Precipitation  17205 non-null  float64
 7   Humidity       17205 non-null  int64
 8   Pressure       17205 non-null  float64
 9   WindDirection  17205 non-null  float64
 10  WindSpeed      17205 non-null  float64
dtypes: datetime64[ns](2), float64(6), int64(3)
memory usage: 1.4 MB

In [11]:
# display top 6 rows
df.head(6)

,PeriodEnd,PeriodStart,Temperature,DHI,DNI,Radiation,Precipitation,Humidity,Pressure,WindDirection,WindSpeed
0,2019-12-31 02:00:00,2019-12-31 01:00:00,22.9,0,0,0.0,47.1,74,917.6,99.0,1.3
1,2019-12-31 03:00:00,2019-12-31 02:00:00,22.3,0,0,0.0,47.8,78,918.3,97.0,1.2
2,2019-12-31 04:00:00,2019-12-31 03:00:00,21.7,0,0,0.0,48.6,83,918.7,108.0,1.0
3,2019-12-31 05:00:00,2019-12-31 04:00:00,21.4,0,0,0.0,48.9,86,918.9,138.0,0.7
4,2019-12-31 06:00:00,2019-12-31 05:00:00,21.1,0,0,0.0,48.4,87,918.8,177.0,0.6
5,2019-12-31 07:00:00,2019-12-31 06:00:00,20.7,0,0,0.0,47.8,88,918.3,182.0,0.7

In [12]:
# Create new features(year, month, day) from start and end time of data collection  
df['YearPS'] = pd.to_datetime(df['PeriodStart']).dt.year
df['YearPE'] = pd.to_datetime(df['PeriodEnd']).dt.year

df['MonthPS'] = pd.to_datetime(df['PeriodStart']).dt.month
df['MonthPE'] = pd.to_datetime(df['PeriodEnd']).dt.month

df['HourPS'] = pd.to_datetime(df['PeriodStart']).dt.hour
df['HourPE'] = pd.to_datetime(df['PeriodEnd']).dt.hour

In [13]:
df.head(5)

,PeriodEnd,PeriodStart,Temperature,DHI,DNI,Radiation,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,YearPS,YearPE,MonthPS,MonthPE,HourPS,HourPE
0,2019-12-31 02:00:00,2019-12-31 01:00:00,22.9,0,0,0.0,47.1,74,917.6,99.0,1.3,2019,2019,12,12,1,2
1,2019-12-31 03:00:00,2019-12-31 02:00:00,22.3,0,0,0.0,47.8,78,918.3,97.0,1.2,2019,2019,12,12,2,3
2,2019-12-31 04:00:00,2019-12-31 03:00:00,21.7,0,0,0.0,48.6,83,918.7,108.0,1.0,2019,2019,12,12,3,4
3,2019-12-31 05:00:00,2019-12-31 04:00:00,21.4,0,0,0.0,48.9,86,918.9,138.0,0.7,2019,2019,12,12,4,5
4,2019-12-31 06:00:00,2019-12-31 05:00:00,21.1,0,0,0.0,48.4,87,918.8,177.0,0.6,2019,2019,12,12,5,6

In [14]:
# create a new feature for sunrise using the function below; fill time for sunrise
def time_to_sunrise(row):
    """
    A function for identifying time of sunrise.
    """
    value= 0
    if row['HourPS'] == 9 and row['HourPE'] == 10 and row['Radiation'] > 0:
        value= '10:00:00'
    elif row['HourPS'] == 10 and row['HourPE'] == 11 and row['Radiation'] > 0:
        value= '11:00:00'
    return value

In [15]:
#Create a new column using the function above
df['Sunrise'] = df.apply(time_to_sunrise, axis=1)
df.head(5)

,PeriodEnd,PeriodStart,Temperature,DHI,DNI,Radiation,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,YearPS,YearPE,MonthPS,MonthPE,HourPS,HourPE,Sunrise
0,2019-12-31 02:00:00,2019-12-31 01:00:00,22.9,0,0,0.0,47.1,74,917.6,99.0,1.3,2019,2019,12,12,1,2,0
1,2019-12-31 03:00:00,2019-12-31 02:00:00,22.3,0,0,0.0,47.8,78,918.3,97.0,1.2,2019,2019,12,12,2,3,0
2,2019-12-31 04:00:00,2019-12-31 03:00:00,21.7,0,0,0.0,48.6,83,918.7,108.0,1.0,2019,2019,12,12,3,4,0
3,2019-12-31 05:00:00,2019-12-31 04:00:00,21.4,0,0,0.0,48.9,86,918.9,138.0,0.7,2019,2019,12,12,4,5,0
4,2019-12-31 06:00:00,2019-12-31 05:00:00,21.1,0,0,0.0,48.4,87,918.8,177.0,0.6,2019,2019,12,12,5,6,0

In [20]:
# create a new feature for sunset using the function below; fill time for sunset
def time_to_sunset(row):
    """
    A function for identifying time of sunset.
    """
    value= 0
    if row['HourPS'] == 22 and row['HourPE'] == 23 and row['Radiation']> 0:
        value= '23:00:00'
    elif row['HourPS'] == 23 and row['HourPE']== 24 and row['Radiation']> 0:
        value= '24:00:00'
    return value

In [21]:
#Create a new column using the function above
df['Sunset'] = df.apply(time_to_sunset, axis=1)

In [22]:
df.Sunset.unique()

array([0, '23:00:00'], dtype=object)

In [23]:
# show summary of our dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17205 entries, 0 to 17204
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PeriodEnd      17205 non-null  datetime64[ns]
 1   PeriodStart    17205 non-null  datetime64[ns]
 2   Temperature    17205 non-null  float64
 3   DHI            17205 non-null  int64
 4   DNI            17205 non-null  int64
 5   Radiation      17205 non-null  float64
 6   Precipitation  17205 non-null  float64
 7   Humidity       17205 non-null  int64
 8   Pressure       17205 non-null  float64
 9   WindDirection  17205 non-null  float64
 10  WindSpeed      17205 non-null  float64
 11  YearPS         17205 non-null  int64
 12  YearPE         17205 non-null  int64
 13  MonthPS        17205 non-null  int64
 14  MonthPE        17205 non-null  int64
 15  HourPS         17205 non-null  int64
 16  HourPE         17205 non-null  int64
 17  Sunrise        17205 non-null  object
 18  Sunset         17205 non-null  object
dtypes: datetime64[ns](2), float64(6), int64(9), object(2)
memory usage: 2.5+ MB

In [24]:
# changing integer values to datetime format
df_new = df.loc[~((df['Radiation'] == 0) & (df['DNI'] == 0) & (df['DHI'] == 0)),:]

In [25]:
# show summary of our dataframe
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9046 entries, 10 to 17204
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PeriodEnd      9046 non-null   datetime64[ns]
 1   PeriodStart    9046 non-null   datetime64[ns]
 2   Temperature    9046 non-null   float64
 3   DHI            9046 non-null   int64
 4   DNI            9046 non-null   int64
 5   Radiation      9046 non-null   float64
 6   Precipitation  9046 non-null   float64
 7   Humidity       9046 non-null   int64
 8   Pressure       9046 non-null   float64
 9   WindDirection  9046 non-null   float64
 10  WindSpeed      9046 non-null   float64
 11  YearPS         9046 non-null   int64
 12  YearPE         9046 non-null   int64
 13  MonthPS        9046 non-null   int64
 14  MonthPE        9046 non-null   int64
 15  HourPS         9046 non-null   int64
 16  HourPE         9046 non-null   int64
 17  Sunrise        9046 non-null   object
 18  Sunset         9046 non-null   object
dtypes: datetime64[ns](2), float64(6), int64(9), object(2)
memory usage: 1.4+ MB

In [26]:
# display 10 random samples of the dataframe
df_new.sample(10)

,PeriodEnd,PeriodStart,Temperature,DHI,DNI,Radiation,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,YearPS,YearPE,MonthPS,MonthPE,HourPS,HourPE,Sunrise,Sunset
12980,2021-06-23 22:00:00,2021-06-23 21:00:00,21.0,193,24,202.0,41.8,82,921.0,187.0,1.8,2021,2021,6,6,21,22,0,0
9447,2021-01-27 17:00:00,2021-01-27 16:00:00,27.2,231,718,884.0,38.7,58,919.2,268.0,1.0,2021,2021,1,1,16,17,0,0
13166,2021-07-01 16:00:00,2021-07-01 15:00:00,24.0,424,15,437.0,35.8,61,924.1,219.0,1.8,2021,2021,7,7,15,16,0,0
7065,2020-10-20 11:00:00,2020-10-20 10:00:00,20.1,2,0,2.0,40.4,75,918.6,126.0,0.3,2020,2020,10,10,10,11,11:00:00,0
12665,2021-06-10 19:00:00,2021-06-10 18:00:00,24.8,290,451,678.0,41.9,69,921.5,29.0,2.2,2021,2021,6,6,18,19,0,0
3837,2020-06-07 23:00:00,2020-06-07 22:00:00,27.6,52,95,68.0,37.3,56,918.3,163.0,2.0,2020,2020,6,6,22,23,0,23:00:00
1906,2020-03-19 12:00:00,2020-03-19 11:00:00,21.1,32,0,32.0,35.7,80,921.6,107.0,1.0,2020,2020,3,3,11,12,0,0
13621,2021-07-20 15:00:00,2021-07-20 14:00:00,25.1,86,830,700.0,35.8,56,923.2,227.0,1.7,2021,2021,7,7,14,15,0,0
6692,2020-10-04 22:00:00,2020-10-04 21:00:00,26.8,141,145,201.0,41.3,58,916.9,208.0,2.6,2020,2020,10,10,21,22,0,0
13385,2021-07-10 19:00:00,2021-07-10 18:00:00,22.6,158,759,823.0,41.8,75,920.8,200.0,1.7,2021,2021,7,7,18,19,0,0

In [27]:
# convert datetime column of endperiod to just date
df_new['Date'] = pd.to_datetime(df_new['PeriodEnd']).dt.normalize()

/tmp/ipykernel_11830/3824839280.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['Date'] = pd.to_datetime(df_new['PeriodEnd']).dt.normalize()

In [28]:
# convert the column (it's a string) to datetime type
dt_series = pd.to_datetime(df_new['Date'])

# create datetime index passing the datetime series
dt_index = pd.DatetimeIndex(dt_series.values)

# 
df_new1 = df_new.set_index(dt_index)

In [29]:
# display first 5 rows
df_new1.head()

,PeriodEnd,PeriodStart,Temperature,DHI,DNI,Radiation,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,YearPS,YearPE,MonthPS,MonthPE,HourPS,HourPE,Sunrise,Sunset,Date
2019-12-31,2019-12-31 12:00:00,2019-12-31 11:00:00,20.5,28,0,28.0,47.2,88,919.5,113.0,0.1,2019,2019,12,12,11,12,0,0,2019-12-31
2019-12-31,2019-12-31 13:00:00,2019-12-31 12:00:00,21.3,127,159,187.0,47.1,87,920.6,1.0,0.5,2019,2019,12,12,12,13,0,0,2019-12-31
2019-12-31,2019-12-31 14:00:00,2019-12-31 13:00:00,21.7,177,493,436.0,47.0,87,921.4,27.0,1.1,2019,2019,12,12,13,14,0,0,2019-12-31
2019-12-31,2019-12-31 15:00:00,2019-12-31 14:00:00,21.9,393,138,484.0,46.9,87,921.7,26.0,1.6,2019,2019,12,12,14,15,0,0,2019-12-31
2019-12-31,2019-12-31 16:00:00,2019-12-31 15:00:00,23.1,463,80,532.0,46.7,84,921.1,3.0,1.2,2019,2019,12,12,15,16,0,0,2019-12-31

In [30]:
# 
df_new1.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9046 entries, 2019-12-31 to 2021-12-16
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PeriodEnd      9046 non-null   datetime64[ns]
 1   PeriodStart    9046 non-null   datetime64[ns]
 2   Temperature    9046 non-null   float64
 3   DHI            9046 non-null   int64
 4   DNI            9046 non-null   int64
 5   Radiation      9046 non-null   float64
 6   Precipitation  9046 non-null   float64
 7   Humidity       9046 non-null   int64
 8   Pressure       9046 non-null   float64
 9   WindDirection  9046 non-null   float64
 10  WindSpeed      9046 non-null   float64
 11  YearPS         9046 non-null   int64
 12  YearPE         9046 non-null   int64
 13  MonthPS        9046 non-null   int64
 14  MonthPE        9046 non-null   int64
 15  HourPS         9046 non-null   int64
 16  HourPE         9046 non-null   int64
 17  Sunrise        9046 non-null   object
 18  Sunset         9046 non-null   object
 19  Date           9046 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(6), int64(9), object(2)
memory usage: 1.4+ MB

In [31]:
# sample daily average for the solar and weather features
df_new1['Daily_radiation'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['Radiation'].mean()
df_new1['Daily_DNI'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['DNI'].mean()
df_new1['Daily_DHI'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['DHI'].mean()
df_new1['Daily_Temp'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['Temperature'].mean()
df_new1['Daily_Precip'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['Precipitation'].mean()
df_new1['Daily_Humidity'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['Humidity'].mean()
df_new1['Daily_Pressure'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['Pressure'].mean()
df_new1['Daily_WindDir'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['WindDirection'].mean()
df_new1['Daily_WindSpeed'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['WindSpeed'].mean()

In [32]:
# display a summary of our dataframe
df_new1.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9046 entries, 2019-12-31 to 2021-12-16
Data columns (total 29 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PeriodEnd        9046 non-null   datetime64[ns]
 1   PeriodStart      9046 non-null   datetime64[ns]
 2   Temperature      9046 non-null   float64
 3   DHI              9046 non-null   int64
 4   DNI              9046 non-null   int64
 5   Radiation        9046 non-null   float64
 6   Precipitation    9046 non-null   float64
 7   Humidity         9046 non-null   int64
 8   Pressure         9046 non-null   float64
 9   WindDirection    9046 non-null   float64
 10  WindSpeed        9046 non-null   float64
 11  YearPS           9046 non-null   int64
 12  YearPE           9046 non-null   int64
 13  MonthPS          9046 non-null   int64
 14  MonthPE          9046 non-null   int64
 15  HourPS           9046 non-null   int64
 16  HourPE           9046 non-null   int64
 17  Sunrise          9046 non-null   object
 18  Sunset           9046 non-null   object
 19  Date             9046 non-null   datetime64[ns]
 20  Daily_radiation  9046 non-null   float64
 21  Daily_DNI        9046 non-null   float64
 22  Daily_DHI        9046 non-null   float64
 23  Daily_Temp       9046 non-null   float64
 24  Daily_Precip     9046 non-null   float64
 25  Daily_Humidity   9046 non-null   float64
 26  Daily_Pressure   9046 non-null   float64
 27  Daily_WindDir    9046 non-null   float64
 28  Daily_WindSpeed  9046 non-null   float64
dtypes: datetime64[ns](3), float64(15), int64(9), object(2)
memory usage: 2.1+ MB

In [33]:
# drop irrelevant features
new_df= df_new1.drop(['PeriodStart', 'YearPS', 'HourPS', 'HourPE', 'Sunrise', 'Sunset', 'MonthPS', 'YearPE'], axis= 1)

In [34]:
# display first 10 rows
new_df.head(10)

,PeriodEnd,Temperature,DHI,DNI,Radiation,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,...,Date,Daily_radiation,Daily_DNI,Daily_DHI,Daily_Temp,Daily_Precip,Daily_Humidity,Daily_Pressure,Daily_WindDir,Daily_WindSpeed
2019-12-31,2019-12-31 12:00:00,20.5,28,0,28.0,47.2,88,919.5,113.0,0.1,...,2019-12-31,455.166667,331.583333,210.5,23.766667,46.75,79.083333,918.991667,79.0,1.408333
2019-12-31,2019-12-31 13:00:00,21.3,127,159,187.0,47.1,87,920.6,1.0,0.5,...,2019-12-31,455.166667,331.583333,210.5,23.766667,46.75,79.083333,918.991667,79.0,1.408333
2019-12-31,2019-12-31 14:00:00,21.7,177,493,436.0,47.0,87,921.4,27.0,1.1,...,2019-12-31,455.166667,331.583333,210.5,23.766667,46.75,79.083333,918.991667,79.0,1.408333
2019-12-31,2019-12-31 15:00:00,21.9,393,138,484.0,46.9,87,921.7,26.0,1.6,...,2019-12-31,455.166667,331.583333,210.5,23.766667,46.75,79.083333,918.991667,79.0,1.408333
2019-12-31,2019-12-31 16:00:00,23.1,463,80,532.0,46.7,84,921.1,3.0,1.2,...,2019-12-31,455.166667,331.583333,210.5,23.766667,46.75,79.083333,918.991667,79.0,1.408333
2019-12-31,2019-12-31 17:00:00,24.6,285,599,817.0,46.5,78,919.9,331.0,1.1,...,2019-12-31,455.166667,331.583333,210.5,23.766667,46.75,79.083333,918.991667,79.0,1.408333
2019-12-31,2019-12-31 18:00:00,25.3,237,687,848.0,46.5,74,919.3,350.0,1.5,...,2019-12-31,455.166667,331.583333,210.5,23.766667,46.75,79.083333,918.991667,79.0,1.408333
2019-12-31,2019-12-31 19:00:00,25.6,217,682,784.0,46.5,72,918.7,14.0,2.1,...,2019-12-31,455.166667,331.583333,210.5,23.766667,46.75,79.083333,918.991667,79.0,1.408333
2019-12-31,2019-12-31 20:00:00,25.8,140,759,683.0,46.5,70,917.4,20.0,2.1,...,2019-12-31,455.166667,331.583333,210.5,23.766667,46.75,79.083333,918.991667,79.0,1.408333
2019-12-31,2019-12-31 21:00:00,25.8,236,331,420.0,46.5,71,916.3,16.0,2.1,...,2019-12-31,455.166667,331.583333,210.5,23.766667,46.75,79.083333,918.991667,79.0,1.408333

In [35]:
# show a summary of the dataframe
new_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9046 entries, 2019-12-31 to 2021-12-16
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PeriodEnd        9046 non-null   datetime64[ns]
 1   Temperature      9046 non-null   float64
 2   DHI              9046 non-null   int64
 3   DNI              9046 non-null   int64
 4   Radiation        9046 non-null   float64
 5   Precipitation    9046 non-null   float64
 6   Humidity         9046 non-null   int64
 7   Pressure         9046 non-null   float64
 8   WindDirection    9046 non-null   float64
 9   WindSpeed        9046 non-null   float64
 10  MonthPE          9046 non-null   int64
 11  Date             9046 non-null   datetime64[ns]
 12  Daily_radiation  9046 non-null   float64
 13  Daily_DNI        9046 non-null   float64
 14  Daily_DHI        9046 non-null   float64
 15  Daily_Temp       9046 non-null   float64
 16  Daily_Precip     9046 non-null   float64
 17  Daily_Humidity   9046 non-null   float64
 18  Daily_Pressure   9046 non-null   float64
 19  Daily_WindDir    9046 non-null   float64
 20  Daily_WindSpeed  9046 non-null   float64
dtypes: datetime64[ns](2), float64(15), int64(4)
memory usage: 1.5 MB

In [36]:
# dropping ALL duplicate values exceept the last value
new_df = new_df[~new_df.Date.duplicated(keep = 'last')]

In [37]:
# show the number of rows and columns available
new_df.shape

(717, 21)

In [38]:
# 
new_df.head(10)

,PeriodEnd,Temperature,DHI,DNI,Radiation,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,...,Date,Daily_radiation,Daily_DNI,Daily_DHI,Daily_Temp,Daily_Precip,Daily_Humidity,Daily_Pressure,Daily_WindDir,Daily_WindSpeed
2019-12-31,2019-12-31 23:00:00,24.1,45,0,45.0,46.9,78,916.1,36.0,1.6,...,2019-12-31,455.166667,331.583333,210.500000,23.766667,46.750000,79.083333,918.991667,79.000000,1.408333
2020-01-01,2020-01-01 23:00:00,25.1,48,10,50.0,45.4,75,915.2,21.0,1.9,...,2020-01-01,484.666667,410.833333,185.250000,24.941667,45.525000,73.583333,918.416667,74.666667,1.516667
2020-01-02,2020-01-02 23:00:00,25.1,33,237,72.0,37.8,75,916.4,116.0,0.5,...,2020-01-02,456.333333,390.083333,219.750000,24.525000,41.516667,76.166667,918.983333,179.000000,1.008333
2020-01-03,2020-01-03 23:00:00,25.6,30,297,78.0,31.3,70,918.4,327.0,0.2,...,2020-01-03,513.000000,546.666667,148.083333,25.183333,31.233333,69.666667,921.125000,191.333333,0.566667
2020-01-04,2020-01-04 23:00:00,24.9,31,295,79.0,27.9,72,918.2,21.0,0.4,...,2020-01-04,534.666667,617.250000,117.916667,24.650000,28.000000,68.416667,921.825000,164.250000,0.791667
2020-01-05,2020-01-05 23:00:00,25.1,36,222,74.0,32.7,74,918.4,29.0,2.5,...,2020-01-05,547.166667,679.166667,97.250000,25.333333,32.141667,70.166667,921.333333,21.333333,2.600000
2020-01-06,2020-01-06 23:00:00,25.0,39,208,74.0,26.7,70,917.2,34.0,1.8,...,2020-01-06,512.250000,526.583333,169.333333,25.216667,29.791667,68.500000,919.975000,19.916667,2.216667
2020-01-07,2020-01-07 23:00:00,25.6,32,312,84.0,31.0,66,917.2,12.0,1.1,...,2020-01-07,540.416667,625.500000,116.583333,25.316667,30.750000,65.666667,919.800000,108.833333,1.158333
2020-01-08,2020-01-08 23:00:00,26.6,31,341,87.0,30.2,59,917.5,237.0,0.1,...,2020-01-08,497.153846,588.307692,100.692308,25.946154,30.200000,59.923077,920.346154,126.692308,0.723077
2020-01-09,2020-01-09 23:00:00,26.5,54,107,70.0,32.9,59,915.8,23.0,0.2,...,2020-01-09,470.153846,481.923077,143.076923,25.869231,33.169231,56.384615,919.469231,164.076923,0.623077

In [39]:
# list out the column names
new_df.columns

Index(['PeriodEnd', 'Temperature', 'DHI', 'DNI', 'Radiation', 'Precipitation',
       'Humidity', 'Pressure', 'WindDirection', 'WindSpeed', 'MonthPE', 'Date',
       'Daily_radiation', 'Daily_DNI', 'Daily_DHI', 'Daily_Temp',
       'Daily_Precip', 'Daily_Humidity', 'Daily_Pressure', 'Daily_WindDir',
       'Daily_WindSpeed'],
      dtype='object')

In [40]:
# select column features
final_df= new_df[['MonthPE', 'Date','Daily_Temp','Daily_Precip', 'Daily_Humidity', 'Daily_Pressure',\
                  'Daily_WindDir','Daily_WindSpeed','Daily_DNI', 'Daily_DHI','Daily_radiation']]

In [41]:
# print the first 5 rows
final_df.head()

,MonthPE,Date,Daily_Temp,Daily_Precip,Daily_Humidity,Daily_Pressure,Daily_WindDir,Daily_WindSpeed,Daily_DNI,Daily_DHI,Daily_radiation
2019-12-31,12,2019-12-31,23.766667,46.750000,79.083333,918.991667,79.000000,1.408333,331.583333,210.500000,455.166667
2020-01-01,1,2020-01-01,24.941667,45.525000,73.583333,918.416667,74.666667,1.516667,410.833333,185.250000,484.666667
2020-01-02,1,2020-01-02,24.525000,41.516667,76.166667,918.983333,179.000000,1.008333,390.083333,219.750000,456.333333
2020-01-03,1,2020-01-03,25.183333,31.233333,69.666667,921.125000,191.333333,0.566667,546.666667,148.083333,513.000000
2020-01-04,1,2020-01-04,24.650000,28.000000,68.416667,921.825000,164.250000,0.791667,617.250000,117.916667,534.666667

In [42]:
# show the number of rows and column
final_df.shape

(717, 11)

In [44]:
# save cleaned dataset
final_df.to_csv('../data/Cleaned_Neiva_Solcast_PT60M.csv')